import Header from "@/component/admin/header";
import RootLayout from "../layout";
export const metadata = {
  title: "Admin@Support Our Heroes",
  description: "Generated by create next app",
};
RootLayout;
export default function Layout({ children }) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}
